# Generated by Django 5.2.15 on 2026-07-04 22:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running_msa', 'Récupération MSA'), ('running_inference', 'Inférence du modèle'), ('completed', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('output_dir', models.CharField(max_length=500)),
                ('query_json_path', models.CharField(max_length=500)),
                ('log_path', models.CharField(max_length=500)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('current_step', models.CharField(blank=True, default='', max_length=200)),
                ('progress_percent', models.FloatField(blank=True, null=True)),
                ('eta_seconds', models.FloatField(blank=True, null=True)),
                ('elapsed_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('best_plddt', models.FloatField(blank=True, null=True)),
                ('result_summary', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
