# Generated by Django 5.2.15 on 2026-09-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0003_derive_paths_from_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attentionrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Extracting"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="predictionjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running_msa", "Fetching MSA"),
                    ("running_inference", "Running inference"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
